name: Build Maven Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 17.0.10+7
          distribution: 'adopt'
      
      - name: Build with Maven
        run: mvn clean install -DskipTests
        
      - name: Build Docker image
        run: docker run --rm -v ${{ github.workspace }}:/app devxci/mbtci-java11-node14 mbt build -s /app
