name: CI

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Maven
        run: sudo apt-get install maven
      
      - name: Build with Maven
        run: mvn clean install

      - name: Pull Docker image
        run: docker pull devxci/mbtci-java11-node14

      - name: Check if mta.yaml exists
        run: ls /home/runner/work/mta-demo/mta-demo/mta.yaml

      - name: Run Docker container
        run: docker run --rm -u $(id -u):$(id -g) -v ${{ github.workspace }}:/app devxci/mbtci-java11-node14 mbt build -s /app/.

      - name: Install Cloud Foundry CLI
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf-cli

      - name: Verify Cloud Foundry CLI installation
        run: cf --version

      - name: Login to Cloud Foundry
        run: cf login --sso -a https://api.cf.us10-001.hana.ondemand.com -o 5c0f872btrial -s dev -u niteshsomvanshi.it@gmail.com -p Pratapgarh@2468

      - name: Deploy to Cloud Foundry
        run: cf deploy com.testing_1.0.0.mtar
