name: CI

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Maven
        run: sudo apt-get install maven
      
      - name: Build with Maven
        run: mvn clean install

      - name: Pull Docker image
        run: docker pull devxci/mbtci-java11-node14

      - name: Run Docker container
        run: docker run --rm -v ${{ github.workspace }}/mta-demo:/app devxci/mbtci-java11-node14 mbt build -s /app/
        
      - name: Log in to Cloud Foundry
        run: cf login -a https://api.cf.us10-001.hana.ondemand.com -o 5c0f872btrial -s dev -u niteshsomvanshi.it@gmail.com -p Nopassword@2468

      - name: Deploy to Cloud Foundry
        run: cf deploy com.testing_1.0.0.mtar
